"use client";
import {
  Stack
} from "@mui/material";
import SwitchThemeUI from "../components/theme/SwitchTheme";
import ThemeProvider from "../components/theme/ThemeProvider";
import "./globals.css";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <ThemeProvider>
        <body>
          <Stack
            justifyContent="end"
            alignContent="center"
            direction="row"
            spacing={2}
          >
            <SwitchThemeUI />
          </Stack>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
